### PR TITLE
atanh limited

### PR DESCRIPTION
**Pull request by maswx**

### CODE REVIEW

**Comment by maswx** [comment]
atanh limited in  SPA

**Comment by xdsopl** [comment]
Why not use ```x <= -1``` and ```x >= 1``` for clamping? Then it would also work for single precision floats.
Where does the value ```19.07``` come from? If I put the upper limit ```double x = 0.999999999999999```, I get ```35.2327```, which is larger than the value ```19.07``` for the upper limit! Or maybe you forgot the factor of two?
Can you cite a source or explain your changes in more detail?
Please fix your code and explain, then I will merge.

**Comment by xdsopl** [comment]
Maybe adding ```atanh_clamped()``` static helper and using that instead of ```std::atanh()``` would be a better idea?

**Comment by maswx** [comment]
Hi, I changed the range of atanh just to avoid `inf`。

**Comment by maswx** [comment]
yes， adding `atanh_clamped()` static helper is a better idea

**Comment by xdsopl** [comment]
I've just added ```atanh_clamped()``` in commit e44cd1aa5ff0422faf1e2e8fb667bc589c0d6f68

**Pull request closed without merging**
